name: 'Docker-Coq Action'
description: 'GitHub Action using Docker-Coq'
author: 'Erik Martin-Dorel'
inputs:
  opam-file:
    description: 'The path of the .opam file, relative to the repo root.'
    required: true
  coq-version:
    description: '"8.X", "latest", or "dev".'
    default: 'latest'
  ocaml-version:
    description: '4.05, 4.07-flambda, or 4.09-flambda'
    default: '4.05'
  custom-script:
    description: 'The main script run in the container; may be overridden.'
    default: |
      opam config list; opam repo list; opam list
      opam pin add -n -y -k path $PACKAGE .
      opam update -y
      opam install -y -v -j 2 $PACKAGE
      opam list
      opam remove $PACKAGE
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-f'
    - ${{ inputs.opam-file }}
    - '-c'
    - ${{ inputs.coq-version }}
    - '-m'
    - ${{ inputs.ocaml-version }}
    - '-s'
    - ${{ inputs.custom-script }}
