name: 'Docker-Coq Action'
description: 'GitHub Action using Docker-Coq'
author: 'Erik Martin-Dorel'
inputs:
  opam_file:
    description: 'The path of the .opam file, relative to the repo root.'
    required: true
  coq_version:
    description: '"8.X", "latest", or "dev".'
    default: 'latest'
  ocaml_version:
    description: 'minimal, 4.07-flambda, or 4.09-flambda'
    default: 'minimal'
  custom_script:
    description: 'The main script run in the container; may be overridden.'
    default: |
      opam config list; opam repo list; opam list
      opam pin add -n -y -k path $PACKAGE .
      opam update -y
      opam install -y -v -j 2 $PACKAGE
      opam list
      opam remove $PACKAGE
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-f'
    - ${{ inputs.opam_file }}
    - '-c'
    - ${{ inputs.coq_version }}
    - '-m'
    - ${{ inputs.ocaml_version }}
    - '-s'
    - ${{ inputs.custom_script }}
